import { InstitutionalUser } from '../types/userManagement';

export const INITIAL_INSTITUTIONAL_USERS: InstitutionalUser[] = [
  {
    id: 'usr-001',
    username: 'ggpd_admin',
    fullName: 'Administrador General GGPD',
    email: 'admin.ggpd@corpoelec.gob.ve',
    role: 'ADMINISTRADOR',
    stateCode: 'NAC',
    unit: 'Gerencia General de Planificación',
    status: 'ACTIVO',
    initialPassword: 'Lunes35.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
    },
    lastLogin: '2026-08-11 11:45',
  },
  {
    id: 'usr-002',
    username: 'j_pacheco',
    fullName: 'Ing. Josue D. Pacheco',
    email: 'j.pacheco@corpoelec.gob.ve',
    role: 'ADMINISTRADOR',
    stateCode: 'NAC',
    unit: 'Desarrollo & Tecnología (GGPD)',
    status: 'ACTIVO',
    initialPassword: 'Pacheco2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
    },
    lastLogin: '2026-08-11 12:10',
  },
  {
    id: 'usr-003',
    username: 'c_favio',
    fullName: 'Catherina Favio',
    email: 'c.favio@corpoelec.gob.ve',
    role: 'GERENCIA',
    stateCode: 'NAC',
    unit: 'División de Planificación de Distribución',
    status: 'ACTIVO',
    initialPassword: 'Favio2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
    },
    lastLogin: '2026-08-10 16:30',
  },
  {
    id: 'usr-004',
    username: 'w_prato',
    fullName: 'Walter Prato',
    email: 'w_prato@corpoelec.gob.ve',
    role: 'ESPECIALISTA',
    stateCode: 'MIR',
    unit: 'División de Planificación',
    status: 'ACTIVO',
    initialPassword: 'Prato2026.',
    permissions: {
      sctis: false,
      tareasMinutas: true,
      planificacion: true,
      scein: false,
    },
    lastLogin: '2026-08-10 14:15',
  },
  {
    id: 'usr-005',
    username: 'j_bencomo',
    fullName: 'Jaime Bencomo',
    email: 'j_bencomo@corpoelec.gob.ve',
    role: 'ESPECIALISTA',
    stateCode: 'CAR',
    unit: 'Redes de Distribución / PRTSEN',
    status: 'ACTIVO',
    initialPassword: 'Bencomo2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: false,
    },
    lastLogin: '2026-08-09 09:20',
  },
  {
    id: 'usr-006',
    username: 'b_gonzalez',
    fullName: 'Blanca González',
    email: 'b.gonzalez@corpoelec.gob.ve',
    role: 'ANALISTA',
    stateCode: 'NAC',
    unit: 'Asistencia de Gerencia',
    status: 'ACTIVO',
    initialPassword: 'Gonzalez2026.',
    permissions: {
      sctis: false,
      tareasMinutas: true,
      planificacion: false,
      scein: false,
    },
    lastLogin: '2026-08-10 11:05',
  },
  {
    id: 'usr-007',
    username: 'j_jimenez',
    fullName: 'Ing. Jorge Jiménez',
    email: 'j.jimenez@corpoelec.gob.ve',
    role: 'GERENCIA',
    stateCode: 'NAC',
    unit: 'Grupo de Seguimiento e Incidencias',
    status: 'ACTIVO',
    initialPassword: 'Jimenez2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
    },
    lastLogin: '2026-08-11 08:45',
  },
  {
    id: 'usr-008',
    username: 'e_tachira',
    fullName: 'Analista Estatal Táchira',
    email: 'analista.tachira@corpoelec.gob.ve',
    role: 'ANALISTA',
    stateCode: 'TAC',
    unit: 'Distribución Estado Táchira',
    status: 'ACTIVO',
    initialPassword: 'Tachira2026.',
    permissions: {
      sctis: true,
      tareasMinutas: false,
      planificacion: false,
      scein: true,
    },
    lastLogin: '2026-08-08 17:00',
  },
  {
    id: 'usr-009',
    username: 'y_cipiran',
    fullName: 'Ing. Y. Cipiran',
    email: 'y.cipiran@corpoelec.gob.ve',
    role: 'ESPECIALISTA',
    stateCode: 'ZUL',
    unit: 'Equipos Indisponibles Zulia',
    status: 'ACTIVO',
    initialPassword: 'Cipiran2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: false,
      scein: true,
    },
    lastLogin: '2026-08-07 10:15',
  },
  {
    id: 'usr-010',
    username: 'a_auditor',
    fullName: 'Auditor ISO 8000 / 27001',
    email: 'auditoria.iso@corpoelec.gob.ve',
    role: 'AUDITOR',
    stateCode: 'NAC',
    unit: 'Auditoría Interna CORPOELEC',
    status: 'ACTIVO',
    initialPassword: 'Auditor2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
    },
    lastLogin: '2026-08-11 10:00',
  },
];
