"""Definición de los diagramas de secuencia SCTIS (datos).

Cada item de mensajes: ("call"|"return", origen, destino, etiqueta)
                      | ("gap", n_filas_extra) | ("nota", texto)
"""

IMPORTACION = dict(
    titulo="Flujo 5.1 — Importación de Tiras Excel (Wizard de 3 pasos)",
    codigo="SCTIS-SEC-01",
    pools=["operador", "admin", "frontend", "api", "ia", "bd", "fs"],
    mensajes=[
        ("call", "operador", "frontend", "1. Sube el archivo .xlsx (POST /import/upload)"),
        ("call", "frontend", "api", "upload: archivo + estado (admin) o estado asignado (operador)"),
        ("call", "api", "fs", "Guarda archivo en /tmp/sctis_imports con token UUID"),
        ("call", "api", "api", "Detecta las hojas visibles del libro"),
        ("return", "api", "frontend", "requires_sheet_selection: lista de hojas + token"),
        ("return", "frontend", "operador", "Pide seleccionar UNA sola hoja (consolidación)"),
        ("gap", 1),
        ("call", "operador", "frontend", "2. Selecciona la hoja (token + sheet_name)"),
        ("call", "frontend", "api", "POST /preview_import (solo esa hoja)"),
        ("call", "api", "bd", "detectar_formato_catalogo: formato del estado (ratio ≥ 0.6)"),
        ("return", "bd", "api", "Formato detectado (mapeo_columnas)"),
        ("call", "api", "fs", "Lee la hoja con HojaMemoria (read_only, data_only)"),
        ("call", "api", "bd", "Consulta common.assets y sctis.causa"),
        ("call", "api", "ia", "Sugerencia de causa oficial ante ambigüedad"),
        ("return", "ia", "api", "Causa más cercana (Google Gemini)"),
        ("call", "api", "api", "detectar_activos_inconsistentes (matching difuso 0.85 / 0.60)"),
        ("call", "api", "bd", "INSERT audit.submissions (PENDING, process sctis_import)"),
        ("return", "api", "frontend", "Preview: causas mapeables, activos inconsistentes, submission_id"),
        ("return", "frontend", "operador", "Muestra homologación de causas y resolución de activos"),
        ("gap", 1),
        ("call", "operador", "frontend", "3. Mapea causas y resuelve activos (mapear / reportar nuevo)"),
        ("call", "frontend", "api", "POST /confirmar_import"),
        ("call", "api", "bd", "INSERT sctis.tira_interrupcion (resuelve activos y despachadores)"),
        ("return", "bd", "api", "Triggers: trg_set_mes, trg_tira_quality, trg_tira_duplicate_check"),
        ("call", "api", "bd", "UPDATE audit.submissions (accepted/rejected, VALIDATED | PARTIAL)"),
        ("call", "api", "bd", "Si rechazados > 0: INSERT tarea_pendiente CORREGIR_DATOS"),
        ("call", "api", "fs", "Genera Excel de corrección (rechazados + motivo)"),
        ("return", "api", "frontend", "Resultado: insertados / rechazados"),
        ("return", "frontend", "operador", "Muestra el resumen final de la carga"),
    ],
)

AUDITORIA = dict(
    titulo="Flujo 5.2 — Auditoría de Cargas",
    codigo="SCTIS-SEC-02",
    pools=["admin", "frontend", "api", "bd", "fs"],
    mensajes=[
        ("call", "admin", "frontend", "GET /admin/auditoria"),
        ("call", "frontend", "api", "listar submissions (filtros: estado, usuario, fecha)"),
        ("call", "api", "bd", "SELECT audit.submissions (PENDING / VALIDATED / PARTIAL)"),
        ("return", "bd", "api", "Submissions + resumen por estado y usuario"),
        ("return", "api", "frontend", "Tabla y resumen agregado"),
        ("gap", 1),
        ("call", "admin", "frontend", "Ver detalle de una submission"),
        ("call", "frontend", "api", "GET /admin/auditoria/<id>"),
        ("call", "api", "bd", "SELECT detalle + rechazados por fila"),
        ("return", "bd", "api", "Rechazados con motivo de error"),
        ("return", "api", "frontend", "Detalle en pantalla"),
        ("gap", 1),
        ("call", "admin", "frontend", "Descargar Excel de corrección"),
        ("call", "frontend", "api", "GET archivo de corrección"),
        ("call", "api", "fs", "Lee / genera el archivo de corrección"),
        ("return", "fs", "api", "Archivo .xlsx"),
        ("return", "api", "frontend", "Archivo descargable"),
    ],
)

CALIDAD = dict(
    titulo="Flujo 5.3 — Control de Calidad ISO 8000 (Triggers de BD)",
    codigo="SCTIS-SEC-03",
    pools=["api", "bd", "trg_mes", "trg_quality", "trg_dup"],
    mensajes=[
        ("call", "api", "bd", "INSERT INTO sctis.tira_interrupcion"),
        ("call", "bd", "trg_mes", "trg_set_mes: computa mes desde fecha_falla"),
        ("return", "trg_mes", "bd", "Campo mes = nombre del mes (AUTO, en mayúsculas)"),
        ("call", "bd", "trg_quality", "trg_tira_quality: evalúa las 9 reglas ISO 8000"),
        ("call", "trg_quality", "bd", "INSERT record_quality_scores (scoring 0-100)"),
        ("call", "bd", "trg_dup", "trg_tira_duplicate_check: detecta duplicados (fecha + circuito + hora)"),
        ("call", "trg_dup", "bd", "INSERT duplicate_groups / duplicate_members (si aplica)"),
        ("return", "trg_dup", "bd", "Análisis de duplicados completado"),
        ("return", "bd", "api", "INSERT confirmado (tira con mes y scoring calculados)"),
    ],
    leyenda=("Reglas de calidad (ISO 8000):",
             ["Completitud · Consistencia · Precisión · Integridad referencial",
              "Detalle de causa · Observaciones · Duplicados · Duración · Mes"]),
)

DASHBOARD = dict(
    titulo="Flujo 5.4 — Dashboard y API de Datos",
    codigo="SCTIS-SEC-04",
    pools=["usuario", "frontend", "api", "bd"],
    mensajes=[
        ("call", "usuario", "frontend", "GET /dashboard (perspectiva: Ing. Eléctrico / Mantto / PM / Data)"),
        ("call", "frontend", "api", "GET /api/dashboard"),
        ("call", "api", "bd", "13 queries: causas, horas, tendencia, sistema, OTRAS (Sankey), circuitos, SE, estados, horario, calidad…"),
        ("return", "bd", "api", "Datos agregados"),
        ("return", "api", "frontend", "JSON con las 13 secciones"),
        ("return", "frontend", "usuario", "Renderiza Chart.js + Plotly (Sankey OTRAS)"),
        ("gap", 1),
        ("call", "usuario", "frontend", "Descargar gráfico como PNG"),
        ("call", "frontend", "frontend", "canvas.toDataURL() / Plotly.downloadImage()"),
        ("return", "frontend", "usuario", "Imagen PNG descargada"),
    ],
)

TAREAS = dict(
    titulo="Flujo 5.5 — Tareas Pendientes (CORREGIR_DATOS | APROBAR_ACTIVO)",
    codigo="SCTIS-SEC-05",
    pools=["sistema", "bd", "admin", "frontend", "api"],
    mensajes=[
        ("call", "sistema", "bd", "INSERT sctis.tarea_pendiente (estado PENDIENTE)"),
        ("return", "bd", "sistema", "Tarea creada con plazos"),
        ("gap", 1),
        ("call", "admin", "frontend", "GET /admin/tareas (filtros por estado y tipo)"),
        ("call", "frontend", "api", "listar tareas"),
        ("call", "api", "bd", "SELECT sctis.tarea_pendiente (PENDIENTES)"),
        ("return", "bd", "api", "Tareas + badges de vencimiento"),
        ("return", "api", "frontend", "Tabla con filtros y vencimientos"),
        ("gap", 1),
        ("call", "admin", "frontend", "Completar / Cancelar tarea"),
        ("call", "frontend", "api", "POST /admin/tareas/<id> (cambiar estado)"),
        ("call", "api", "bd", "UPDATE estado (COMPLETADA | CANCELADA)"),
        ("return", "bd", "api", "OK"),
        ("return", "api", "frontend", "Refresca la lista"),
    ],
)

APRENDIZAJE = dict(
    titulo="Flujo 5.6 — Aprendizaje del Diccionario de Activos (ISO 8000-110)",
    codigo="SCTIS-SEC-06",
    pools=["operador", "frontend", "api", "bd"],
    mensajes=[
        ("call", "operador", "frontend", "Previsualización: nombre fuera de norma identificado"),
        ("call", "frontend", "api", "Mapear activo: nombre reportado → activo oficial"),
        ("call", "api", "bd", "INSERT sctis.asset_alias (estado, tipo, nombre, se_referencia, activo, usuario)"),
        ("return", "bd", "api", "Sinónimo guardado (UNIQUE por estado/tipo/nombre)"),
        ("return", "api", "frontend", "Emparejado y memorizado"),
        ("gap", 1),
        ("call", "operador", "frontend", "Carga futura: el mismo nombre vuelve a aparecer"),
        ("call", "frontend", "api", "POST /preview_import"),
        ("call", "api", "bd", "SELECT sctis.asset_alias (antes del matching difuso)"),
        ("return", "bd", "api", "Alias encontrado (estado + tipo + se_referencia)"),
        ("return", "api", "frontend", "Se resuelve automáticamente, sin preguntar al usuario"),
    ],
)

APROBACION = dict(
    titulo="Flujo 5.7 — Revisión y Aprobación de Activos Nuevos (Control de Cambios)",
    codigo="SCTIS-SEC-07",
    pools=["operador", "frontend", "api", "bd", "admin"],
    mensajes=[
        ("call", "operador", "frontend", "Marca 'Reportar como nueva' (no está en catálogo)"),
        ("call", "frontend", "api", "POST /confirmar_import (se_nuevos / ci_nuevos)"),
        ("call", "api", "bd", "INSERT sctis.asset_request (PENDIENTE, preclasificado, candidato) — tira con IDs NULL"),
        ("call", "api", "bd", "INSERT tarea_pendiente APROBAR_ACTIVO (para el admin del estado)"),
        ("return", "bd", "api", "OK (la carga no se bloquea)"),
        ("return", "api", "frontend", "Carga completada con activos por aprobar"),
        ("gap", 1),
        ("call", "admin", "frontend", "GET /admin/activos (bandeja de revisión)"),
        ("call", "frontend", "api", "listar_activos (pendientes del estado)"),
        ("call", "api", "bd", "SELECT sctis.asset_request + activo candidato"),
        ("return", "bd", "api", "Solicitudes preclasificadas (probable typo / alias / nuevo)"),
        ("return", "api", "frontend", "Bandeja con sugerencias y filas afectadas"),
        ("gap", 1),
        ("call", "admin", "frontend", "Decide: Aprobar · Es alias · Corregir · Rechazar"),
        ("call", "frontend", "api", "POST aprobar_activo | asignar_alias | corregir_activo | rechazar_activo"),
        ("call", "api", "bd", "INSERT common.assets (SE code UPPER(nombre); CT 'SE :: NOMBRE')"),
        ("call", "api", "bd", "UPDATE tira_interrupcion: backfill (subestacion_id / circuito_id)"),
        ("call", "api", "bd", "INSERT sctis.asset_alias (memoriza el nombre reportado)"),
        ("call", "api", "bd", "UPDATE asset_request (decided_by, decided_at, comentario) + completa tareas si no quedan"),
        ("return", "bd", "api", "Trazabilidad registrada (ISO 27001)"),
        ("return", "api", "frontend", "Solicitud resuelta; cargas futuras se resuelven solas"),
    ],
    leyenda=("Zonas de la operación:",
             ["ZONA A — Ingestión de datos: no bloqueada, el operador siempre puede cargar",
              "ZONA B — Gobierno del catálogo: supervisada por el administrador (ISO 9001)"]),
)

LOGIN = dict(
    titulo="Proceso — Autenticación y Control de Acceso",
    codigo="SCTIS-SEC-08",
    pools=["operador", "frontend", "api", "bd"],
    mensajes=[
        ("call", "operador", "frontend", "POST /login (usuario + contraseña)"),
        ("call", "frontend", "api", "autenticar credenciales"),
        ("call", "api", "bd", "SELECT user_profiles + user_roles + contador de intentos"),
        ("return", "bd", "api", "Hash de contraseña e intentos fallidos"),
        ("call", "api", "api", "Valida bcrypt + política de bloqueo (5 fallos / 30 min)"),
        ("return", "api", "frontend", "Sesión (token/cookie) + perfil (rol, estado asignado)"),
        ("return", "frontend", "operador", "Acceso concedido — RLS filtra los datos por estado"),
        ("call", "operador", "bd", "Operaciones: las RLS policies restringen filas por estado (admin total)"),
    ],
    leyenda=("Roles:",
             ["ggpd_admin — administrador total (todos los estados y módulos admin)",
              "operador.amazona — editor, solo su estado (AMAZONAS)",
              "supervisor — por ahora con las mismas funciones del administrador"]),
)

DIAGRAMAS = [
    IMPORTACION,
    AUDITORIA,
    CALIDAD,
    DASHBOARD,
    TAREAS,
    APRENDIZAJE,
    APROBACION,
    LOGIN,
]
