import { InstitutionalUser } from '../types/userManagement';

export const INITIAL_INSTITUTIONAL_USERS: InstitutionalUser[] = [
  {
    id: 'usr-001',
    username: 'ggpd_admin',
    fullName: 'Administrador General GGPD',
    email: 'admin.ggpd@corpoelec.gob.ve',
    googleEmail: 'bk.ggpd.corpoelec@gmail.com',
    role: 'ADMINISTRADOR',
    stateCode: 'NAC',
    unit: 'Gerencia General de Planificación',
    status: 'ACTIVO',
    initialPassword: 'admin2026!.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-14 11:45',
  },
  {
    id: 'usr-002',
    username: 'j_pacheco',
    fullName: 'Josue Pacheco',
    email: 'j.pacheco@corpoelec.gob.ve',
    googleEmail: 'josue.pacheco.ggpd@gmail.com',
    role: 'ADMINISTRADOR',
    stateCode: 'NAC',
    unit: 'Desarrollo & Tecnología (GGPD)',
    status: 'ACTIVO',
    initialPassword: 'Pacheco2026!.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-14 12:10',
  },
  {
    id: 'usr-003',
    username: 'a_correa',
    fullName: 'Adrian Correa',
    email: 'a.correa@corpoelec.gob.ve',
    googleEmail: 'adrian.correa.ggpd@gmail.com',
    role: 'GERENCIA',
    stateCode: 'NAC',
    unit: 'Gerencia General de Planificación de Distribución (GGPD)',
    status: 'ACTIVO',
    initialPassword: 'Correa2026!.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-14 12:00',
  },
  {
    id: 'usr-004',
    username: 'c_favio',
    fullName: 'Catherina Favio',
    email: 'c.favio@corpoelec.gob.ve',
    googleEmail: 'catherina.favio.ggpd@gmail.com',
    role: 'GERENCIA',
    stateCode: 'NAC',
    unit: 'División de Planificación de Distribución',
    status: 'ACTIVO',
    initialPassword: 'Favio2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-10 16:30',
  },
  {
    id: 'usr-005',
    username: 'w_prato',
    fullName: 'Walter Prato',
    email: 'w_prato@corpoelec.gob.ve',
    googleEmail: 'walter.prato.miranda@gmail.com',
    role: 'ESPECIALISTA',
    stateCode: 'MIR',
    unit: 'División de Planificación',
    status: 'ACTIVO',
    initialPassword: 'Prato2026.',
    permissions: {
      sctis: false,
      tareasMinutas: true,
      planificacion: true,
      scein: false,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-10 14:15',
  },
  {
    id: 'usr-006',
    username: 'j_bencomo',
    fullName: 'Jaime Bencomo',
    email: 'j_bencomo@corpoelec.gob.ve',
    googleEmail: 'jaime.bencomo.carabobo@gmail.com',
    role: 'ESPECIALISTA',
    stateCode: 'CAR',
    unit: 'Redes de Distribución / PRTSEN',
    status: 'ACTIVO',
    initialPassword: 'Bencomo2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: false,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-09 09:20',
  },
  {
    id: 'usr-007',
    username: 'b_gonzalez',
    fullName: 'Blanca González',
    email: 'b.gonzalez@corpoelec.gob.ve',
    googleEmail: 'blanca.gonzalez.asistencia@gmail.com',
    role: 'ANALISTA',
    stateCode: 'NAC',
    unit: 'Asistencia de Gerencia',
    status: 'ACTIVO',
    initialPassword: 'Gonzalez2026.',
    permissions: {
      sctis: false,
      tareasMinutas: true,
      planificacion: false,
      scein: false,
      gdriveRepo: false,
    },
    lastLogin: '2026-08-10 11:05',
  },
  {
    id: 'usr-008',
    username: 'j_jimenez',
    fullName: 'Ing. Jorge Jiménez',
    email: 'j.jimenez@corpoelec.gob.ve',
    googleEmail: 'jorge.jimenez.sen@gmail.com',
    role: 'GERENCIA',
    stateCode: 'NAC',
    unit: 'Grupo de Seguimiento e Incidencias',
    status: 'ACTIVO',
    initialPassword: 'Jimenez2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-11 08:45',
  },
  {
    id: 'usr-009',
    username: 'e_tachira',
    fullName: 'Analista Estatal Táchira',
    email: 'analista.tachira@corpoelec.gob.ve',
    googleEmail: 'distribucion.tachira.sala@gmail.com',
    role: 'ANALISTA',
    stateCode: 'TAC',
    unit: 'Distribución Estado Táchira',
    status: 'ACTIVO',
    initialPassword: 'Tachira2026.',
    permissions: {
      sctis: true,
      tareasMinutas: false,
      planificacion: false,
      scein: true,
      gdriveRepo: false,
    },
    lastLogin: '2026-08-08 17:00',
  },
  {
    id: 'usr-010',
    username: 'y_cipiran',
    fullName: 'Ing. Y. Cipiran',
    email: 'y.cipiran@corpoelec.gob.ve',
    googleEmail: 'yvan.ciprian.zulia@gmail.com',
    role: 'ESPECIALISTA',
    stateCode: 'ZUL',
    unit: 'Equipos Indisponibles Zulia',
    status: 'ACTIVO',
    initialPassword: 'Cipiran2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: false,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-07 10:15',
  },
  {
    id: 'usr-011',
    username: 'a_auditor',
    fullName: 'Auditor ISO 8000 / 27001',
    email: 'auditoria.iso@corpoelec.gob.ve',
    googleEmail: 'auditoria.iso.corpoelec@gmail.com',
    role: 'AUDITOR',
    stateCode: 'NAC',
    unit: 'Auditoría Interna CORPOELEC',
    status: 'ACTIVO',
    initialPassword: 'Auditor2026.',
    permissions: {
      sctis: true,
      tareasMinutas: true,
      planificacion: true,
      scein: true,
      gdriveRepo: true,
    },
    lastLogin: '2026-08-11 10:00',
  },
  // =========================================================================
  // 25 COORDINACIONES ESTADALES DE DISTRIBUCIÓN — PERFIL VISOR_ESTADAL (SIGI)
  // =========================================================================
  {
    id: 'usr-011',
    username: 'coord_capital',
    fullName: 'Coordinación Estadal Distrito Capital (GGPD)',
    email: 'coord.capital@corpoelec.gob.ve',
    googleEmail: 'distribucion.capital.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'DCA',
    unit: 'Coordinación de Planificación Capital',
    status: 'ACTIVO',
    initialPassword: 'Capital2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 08:30',
  },
  {
    id: 'usr-012',
    username: 'coord_miranda',
    fullName: 'Coordinación Estadal Miranda (GGPD)',
    email: 'coord.miranda@corpoelec.gob.ve',
    googleEmail: 'distribucion.miranda.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'MIR',
    unit: 'Coordinación de Planificación Miranda',
    status: 'ACTIVO',
    initialPassword: 'Miranda2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 08:35',
  },
  {
    id: 'usr-013',
    username: 'coord_laguaira',
    fullName: 'Coordinación Estadal La Guaira (GGPD)',
    email: 'coord.laguaira@corpoelec.gob.ve',
    googleEmail: 'distribucion.laguaira.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'LGU',
    unit: 'Coordinación de Planificación La Guaira',
    status: 'ACTIVO',
    initialPassword: 'Laguaira2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 08:40',
  },
  {
    id: 'usr-014',
    username: 'coord_carabobo',
    fullName: 'Coordinación Estadal Carabobo (GGPD)',
    email: 'coord.carabobo@corpoelec.gob.ve',
    googleEmail: 'distribucion.carabobo.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'CAR',
    unit: 'Coordinación de Planificación Carabobo',
    status: 'ACTIVO',
    initialPassword: 'Carabobo2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 08:45',
  },
  {
    id: 'usr-015',
    username: 'coord_aragua',
    fullName: 'Coordinación Estadal Aragua (GGPD)',
    email: 'coord.aragua@corpoelec.gob.ve',
    googleEmail: 'distribucion.aragua.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'ARA',
    unit: 'Coordinación de Planificación Aragua',
    status: 'ACTIVO',
    initialPassword: 'Aragua2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 08:50',
  },
  {
    id: 'usr-016',
    username: 'coord_zulia',
    fullName: 'Coordinación Estadal Zulia (GGPD)',
    email: 'coord.zulia@corpoelec.gob.ve',
    googleEmail: 'distribucion.zulia.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'ZUL',
    unit: 'Coordinación de Planificación Zulia',
    status: 'ACTIVO',
    initialPassword: 'Zulia2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 08:55',
  },
  {
    id: 'usr-017',
    username: 'coord_falcon',
    fullName: 'Coordinación Estadal Falcón (GGPD)',
    email: 'coord.falcon@corpoelec.gob.ve',
    googleEmail: 'distribucion.falcon.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'FAL',
    unit: 'Coordinación de Planificación Falcón',
    status: 'ACTIVO',
    initialPassword: 'Falcon2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:00',
  },
  {
    id: 'usr-018',
    username: 'coord_lara',
    fullName: 'Coordinación Estadal Lara (GGPD)',
    email: 'coord.lara@corpoelec.gob.ve',
    googleEmail: 'distribucion.lara.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'LAR',
    unit: 'Coordinación de Planificación Lara',
    status: 'ACTIVO',
    initialPassword: 'Lara2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:05',
  },
  {
    id: 'usr-019',
    username: 'coord_yaracuy',
    fullName: 'Coordinación Estadal Yaracuy (GGPD)',
    email: 'coord.yaracuy@corpoelec.gob.ve',
    googleEmail: 'distribucion.yaracuy.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'YAR',
    unit: 'Coordinación de Planificación Yaracuy',
    status: 'ACTIVO',
    initialPassword: 'Yaracuy2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:10',
  },
  {
    id: 'usr-020',
    username: 'coord_tachira',
    fullName: 'Coordinación Estadal Táchira (GGPD)',
    email: 'coord.tachira@corpoelec.gob.ve',
    googleEmail: 'distribucion.tachira.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'TAC',
    unit: 'Coordinación de Planificación Táchira',
    status: 'ACTIVO',
    initialPassword: 'Tachira2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:15',
  },
  {
    id: 'usr-021',
    username: 'coord_merida',
    fullName: 'Coordinación Estadal Mérida (GGPD)',
    email: 'coord.merida@corpoelec.gob.ve',
    googleEmail: 'distribucion.merida.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'MER',
    unit: 'Coordinación de Planificación Mérida',
    status: 'ACTIVO',
    initialPassword: 'Merida2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:20',
  },
  {
    id: 'usr-022',
    username: 'coord_trujillo',
    fullName: 'Coordinación Estadal Trujillo (GGPD)',
    email: 'coord.trujillo@corpoelec.gob.ve',
    googleEmail: 'distribucion.trujillo.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'TRU',
    unit: 'Coordinación de Planificación Trujillo',
    status: 'ACTIVO',
    initialPassword: 'Trujillo2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:25',
  },
  {
    id: 'usr-023',
    username: 'coord_barinas',
    fullName: 'Coordinación Estadal Barinas (GGPD)',
    email: 'coord.barinas@corpoelec.gob.ve',
    googleEmail: 'distribucion.barinas.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'BAR',
    unit: 'Coordinación de Planificación Barinas',
    status: 'ACTIVO',
    initialPassword: 'Barinas2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:30',
  },
  {
    id: 'usr-024',
    username: 'coord_portuguesa',
    fullName: 'Coordinación Estadal Portuguesa (GGPD)',
    email: 'coord.portuguesa@corpoelec.gob.ve',
    googleEmail: 'distribucion.portuguesa.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'POR',
    unit: 'Coordinación de Planificación Portuguesa',
    status: 'ACTIVO',
    initialPassword: 'Portuguesa2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:35',
  },
  {
    id: 'usr-025',
    username: 'coord_cojedes',
    fullName: 'Coordinación Estadal Cojedes (GGPD)',
    email: 'coord.cojedes@corpoelec.gob.ve',
    googleEmail: 'distribucion.cojedes.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'COJ',
    unit: 'Coordinación de Planificación Cojedes',
    status: 'ACTIVO',
    initialPassword: 'Cojedes2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:40',
  },
  {
    id: 'usr-026',
    username: 'coord_guarico',
    fullName: 'Coordinación Estadal Guárico (GGPD)',
    email: 'coord.guarico@corpoelec.gob.ve',
    googleEmail: 'distribucion.guarico.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'GUA',
    unit: 'Coordinación de Planificación Guárico',
    status: 'ACTIVO',
    initialPassword: 'Guarico2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:45',
  },
  {
    id: 'usr-027',
    username: 'coord_apure',
    fullName: 'Coordinación Estadal Apure (GGPD)',
    email: 'coord.apure@corpoelec.gob.ve',
    googleEmail: 'distribucion.apure.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'APU',
    unit: 'Coordinación de Planificación Apure',
    status: 'ACTIVO',
    initialPassword: 'Apure2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:50',
  },
  {
    id: 'usr-028',
    username: 'coord_anzoategui',
    fullName: 'Coordinación Estadal Anzoátegui (GGPD)',
    email: 'coord.anzoategui@corpoelec.gob.ve',
    googleEmail: 'distribucion.anzoategui.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'ANZ',
    unit: 'Coordinación de Planificación Anzoátegui',
    status: 'ACTIVO',
    initialPassword: 'Anzoategui2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 09:55',
  },
  {
    id: 'usr-029',
    username: 'coord_monagas',
    fullName: 'Coordinación Estadal Monagas (GGPD)',
    email: 'coord.monagas@corpoelec.gob.ve',
    googleEmail: 'distribucion.monagas.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'MON',
    unit: 'Coordinación de Planificación Monagas',
    status: 'ACTIVO',
    initialPassword: 'Monagas2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:00',
  },
  {
    id: 'usr-030',
    username: 'coord_sucre',
    fullName: 'Coordinación Estadal Sucre (GGPD)',
    email: 'coord.sucre@corpoelec.gob.ve',
    googleEmail: 'distribucion.sucre.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'SUC',
    unit: 'Coordinación de Planificación Sucre',
    status: 'ACTIVO',
    initialPassword: 'Sucre2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:05',
  },
  {
    id: 'usr-031',
    username: 'coord_nuevaesparta',
    fullName: 'Coordinación Estadal Nueva Esparta (GGPD)',
    email: 'coord.nuevaesparta@corpoelec.gob.ve',
    googleEmail: 'distribucion.nuevaesparta.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'NES',
    unit: 'Coordinación de Planificación Nueva Esparta',
    status: 'ACTIVO',
    initialPassword: 'Nuevaesparta2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:10',
  },
  {
    id: 'usr-032',
    username: 'coord_bolivar',
    fullName: 'Coordinación Estadal Bolívar (GGPD)',
    email: 'coord.bolivar@corpoelec.gob.ve',
    googleEmail: 'distribucion.bolivar.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'BOL',
    unit: 'Coordinación de Planificación Bolívar',
    status: 'ACTIVO',
    initialPassword: 'Bolivar2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:15',
  },
  {
    id: 'usr-033',
    username: 'coord_amazonas',
    fullName: 'Coordinación Estadal Amazonas (GGPD)',
    email: 'coord.amazonas@corpoelec.gob.ve',
    googleEmail: 'distribucion.amazonas.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'AMA',
    unit: 'Coordinación de Planificación Amazonas',
    status: 'ACTIVO',
    initialPassword: 'Amazonas2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:20',
  },
  {
    id: 'usr-034',
    username: 'coord_deltaamacuro',
    fullName: 'Coordinación Estadal Delta Amacuro (GGPD)',
    email: 'coord.deltaamacuro@corpoelec.gob.ve',
    googleEmail: 'distribucion.deltaamacuro.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'DEL',
    unit: 'Coordinación de Planificación Delta Amacuro',
    status: 'ACTIVO',
    initialPassword: 'Deltaamacuro2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:25',
  },
  {
    id: 'usr-035',
    username: 'coord_esequibo',
    fullName: 'Proyecto Especial de Electrificación Guayana Esequiba (GGPD)',
    email: 'electrificacion.esequibo@corpoelec.gob.ve',
    googleEmail: 'esequibo.electrificacion.ggpd@gmail.com',
    role: 'VISOR_ESTADAL',
    stateCode: 'GEQ',
    unit: 'Comisión Especial de Planificación Guayana Esequiba',
    status: 'ACTIVO',
    initialPassword: 'Esequibo2026!.',
    permissions: { sctis: false, tareasMinutas: false, planificacion: false, scein: false, gdriveRepo: false },
    lastLogin: '2026-08-14 10:30',
  },
];
